replicaCount: 1

image:
  repository: kalpithasrinivas/go-web-app
  pullPolicy: IfNotPresent
  tag: "22537880153"

service:
  type: NodePort
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix